name: Ruby CI

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Test Ruby ${{ matrix.ruby }}

    strategy:
      matrix:
        ruby-version: ['3.1', '3.0', '2.7']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run the default task
      run: bundle exec rake
